---
title: "ATB and Steroid contents of other category"
author: "Rebecca Hoyd"
date: "June 19, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(flextable)
library(UpSetR)
library(glue)
library(tibble)
library(tidyverse)
library(dagitty)
library(ggdag)
library(causaleffect)
library(igraph)
library(rgl)
#devtools::install_github("malcolmbarrett/ggdag")
```

# Load data
```{r}
db <- readRDS("db.RDS")

genbreak <- readRDS("allmeds-for-upset.RDS")

sterkey <- read.table("steroid-dbid-key.tsv")

sterkey <- sterkey %>%
  select(-Drug.name)

sterkey <- sterkey[!duplicated(sterkey),]

```

# Functions 
```{r}
check.window <- function(vect, per){
  wind <- per[1]:per[2]
  wind <- glue_collapse(as.character(wind), sep = ",|,")
  wind <- paste(",", wind, ",", sep = "")
  ifelse(grepl(pattern = wind, x = vect), 1, 0)
}
```

# Creating needed columns

```{r}
abxclasses <- c("BetaLactam", "Macrolide",  "Other.Antibacterial", "Fluoroquinolone", "Tetracycline", "Vancomycin", "Trimethoprim", "Clindamycin", "Metronidazole")

statesofinterest <- c(abxclasses, as.character(sterkey$Generic.ID))

edges <- c(-28,28)

for(s in statesofinterest){
  db[[paste(s, ".to.start", sep = "")]] <- paste(",", db[[paste(s, ".to.start", sep = "")]], ",", sep = "") 
  db[[s]] <- check.window(db[[paste(s, ".to.start", sep = "")]], edges)
}

db$Other.Steroid <- ifelse(db$Betamthasone == 1 | db$Fludrocortisone == 1 | db$Prednisolone == 1, 1, 0)

db <- db %>%
  mutate(abx.28.28 = check.window(paste(",", abxdays.to.iostart, ",", sep = ""), edges),
         steroid.28.28 = check.window(paste(",", sterdays.to.start, ",", sep = ""), edges))
```

# Table S1)

```{r}
othatb.tab <- db %>%
  filter(!is.na(oth.presc.28)) %>%
  group_by(oth.presc.28) %>%
  tally() %>%
  mutate(ATB = oth.presc.28) %>%
  select(ATB, n)
 

othatb.tab %>%
  flextable()
```

```{r}
#write.csv(othatb.tab, "../tables/supplemental/other-atb-quantities.csv")
```

# Table S2)

```{r}
othster.tab <- db %>%
  filter(Other.Steroid == 1) %>%
  summarise(Betamethasone = sum(Betamthasone),
            Fludrocortisone = sum(Fludrocortisone), 
            Prednisolone = sum(Prednisolone),
            Total = sum(Other.Steroid)) %>%
  t() %>%
  as.data.frame() %>%
  rownames_to_column(var = "Steroid") %>%
  mutate(n = as.integer(V1)) %>%
  select(-V1)

othster.tab %>%
  flextable()
```

```{r}
#write.csv(othster.tab, "../tables/supplemental/other-steroid-quantities.csv")
```

# Figure S1)
```{r prep for upset}
meds_iostart <- c("h2b_iostart", "nsaid_iostart", "ppi", "statin", "steroid.28.28", "abx.28.28")

dat.for.upset <- db %>%
  select(meds_iostart)

colnames(dat.for.upset) <- c("H2B", "NSAIDs", "PPI", "Statins", "Steroids", "Antibiotics")
```

```{r save upset, eval = FALSE}
#png("../figures/supplemental/upset_all-meds-confounding.png", units = "in", height = 5, width = 8, res = 600)

upset(dat.for.upset, main.bar.color = "darkred", mainbar.y.label = "Number of Patients", matrix.color = "dark blue", sets.x.label = "")

#dev.off()
```

# Figure S2)
```{r}
dat.for.upset <- db %>%
  select(abxclasses)

colnames(dat.for.upset) <- c("BetaLactam", "Macrolide",  "Other Antibacterial", "Fluoroquinolone", "Tetracycline", "Vancomycin", "Trimethoprim", "Clindamycin", "Metronidazole")
```

```{r, eval = FALSE}
#png("../figures/supplemental/upset_atb.png", units = "in", height = 5, width = 8, res = 600)

upset(dat.for.upset, main.bar.color = "darkred", mainbar.y.label = "Number of Patients", matrix.color = "dark blue", sets.x.label = "", nsets = 9)
#dev.off()
```

# Figure S3)
```{r}
dat.for.upset <- db %>%
  select(Triamcinolone, Prednisone, Hydrocortisone, Methylprednisone, Dexamethosone, Hydrocortisone, Other.Steroid)

colnames(dat.for.upset)[6] <- "Other Steroid"
```

```{r, eval = FALSE}
#png("../figures/supplemental/upset_steroid.png", units = "in", height = 5, width = 8, res = 600)

upset(dat.for.upset, main.bar.color = "darkred", mainbar.y.label = "Number of Patients", matrix.color = "dark blue", sets.x.label = "", nsets = 7)

#dev.off()
```

# Figure S4)

```{r}
blac <- c("Penicillin-V", "Amoxicillin", "Amoxicillin-Clavulanate", "Ampicillin", "Ampicillin-Sulbactam","Piperacillin-Tazobactam", "Cephalexin", "Ceftriaxone", "Cefepime", "Aztreonam")

FQ <- c("Ciprofloxacin", "Levofloxacin", "Moxifloxacin")

macabx <- c("Azithromycin", "Clarithromycin", "Erythromycin")

tetabx <- c("Doxycycline", "Minocycline")

othabx <- c("Linezolid", "Daptomycin")

antvir <- c("Acyclovir", "Ganciclovir", "Valacyclovir", "Valaciclovir", "Valganciclovir", "Foscarnet", "Oseltamivir")

antfun <- c("Fluconazole", "Voriconazole", "Posaconazole", "Caspofungin", "Micafungin")
```

```{r}
genblacs <- genbreak %>%
  select(blac)

genfq <- genbreak %>%
  select(FQ)

genmac <- genbreak %>%
  select(macabx)

gentet <- genbreak %>%
  select(tetabx)
```

```{r}
#png("../figures/supplemental/S4_betalactams.png")

upset(genblacs, main.bar.color = "darkred", mainbar.y.label = "Number of Patients", matrix.color = "dark blue", sets.x.label = "", nsets = 10)

#dev.off()
```

```{r}
#png("../figures/supplemental/S4_FQ.png")

upset(genfq, main.bar.color = "darkred", mainbar.y.label = "Number of Patients", matrix.color = "dark blue", sets.x.label = "", nsets = 10)

#dev.off()
```

```{r}
#png("../figures/supplemental/S4_macrolides.png")

upset(genmac, main.bar.color = "darkred", mainbar.y.label = "Number of Patients", matrix.color = "dark blue", sets.x.label = "", nsets = 10)

#dev.off()
```

```{r}
#png("../figures/supplemental/S4_tetracyclines.png")

upset(gentet, main.bar.color = "darkred", mainbar.y.label = "Number of Patients", matrix.color = "dark blue", sets.x.label = "", nsets = 10)

#dev.off()
```

# Figure S1 causual model Mitchell Muniak

```{r}

letters.1 <- c(letters, "aa")

```

```{r, out.width="100%", out.height="100%"}

g <- graph.formula("ATB" -+ "Microbiome",
                   "Microbiome" -+ "T-cell Mediated Inflammation" -+ "IO Response",
                   "Prostaglandin Inflammation" -+ "Microbiome" -+  "T-cell Mediated Inflammation",
                   "PPI" -+ "Microbiome",
                   "H2B" -+ "Microbiome",
                   "NSAIDs" -+ "Prostaglandin Inflammation",
                   "Corticosteroids" -+ "T-cell Mediated Inflammation",
                   "Corticosteroids" -+ "Prostaglandin Inflammation",
                   "Age" -+ "Prostaglandin Inflammation",
                   "Age" -+ "T-cell Mediated Inflammation",
                   "Age" -+ "Microbiome",
                   "Staging" -+ "Prostaglandin Inflammation",
                   "ECOG" -+ "Prostaglandin Inflammation",
                   "ECOG" -+ "T-cell Mediated Inflammation",
                   "ECOG" -+ "Microbiome",
                   "BMI" -+ "Prostaglandin Inflammation",
                   "BMI" -+ "T-cell Mediated Inflammation",
                   "BMI" -+ "Microbiome",
                   "CCI" -+ "Corticosteroids",
                   "CCI" -+ "H2B",
                   "CCI" -+ "PPI",
                   "CCI" -+ "NSAIDs",
                   "CCI" -+ "ATB",
                   "CCI" -+ "ECOG",
                   "Prostaglandin Inflammation" -+ "T-cell Mediated Inflammation",
                   "ICI Response" -+ "Overall Survival",
                   
                      simplify = TRUE)

E(g)$label = letters.1[1:ecount(g)]
plot(g)

plot.igraph(g, size = 90)

tkplot(g)
```
