---
title: "Untitled"
author: "Rebecca Hoyd"
date: "April 10, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(ggplot2)
library(ggtree)
library(phylogram)
library(rotl)
library(dplyr)
library(forcats)
library(gridExtra)
library(tidyr)
library(phytools)
```

# loading data 

```{r access data from otl}
hazardtable <- readRDS("hazard-table.RDS")
antiorder <- hazardtable %>%
  arrange(Average.Rank) 
antiorder <- antiorder$Antibacterial

taxa <- read.csv("fig5_ottid.csv", stringsAsFactors = FALSE) 
tree <- read.tree("labelled_supertree_ottnames.tre")
```

```{r}
litmics <- c("akkermansia muciniphila",
                                   "parabacteroides distasonis",
                                   "bacteroides nordii",
                                   "bacteroides clarus",
                                   "clostridium bolteae",
                                   "cloacibacilis porcorum",
                                   "ruminococcus bromii",
                                   "porphyromonas pasteri",
                                   "clostridium hungatei",
                                   "gardnerella vaginalis",
                                   "prevotella histicola",
                                   "desulfovibrio alaskensis",
                                   "collinsella aerofaciens",
                                   "bifidobacterium adolescentis",
                                   "klebsiella pneumoniae",
                                   "bifidobacterium longum",
                                   "blautia obeum",
                                   "roseburia intestinalis")

# The following code could be used to directly get information from the Open Tree of Life. We choose to use the version of the tree represented with  OTT IDs version 3.0 and the synthetic tree version 10.4, which are no longer accessibly with this code. The unique names returned by this code were used to determine which OTT ID's were needed to recreated the tree ourselves.

# taxa <- tnrs_match_names(names = litmics)
# 
# tree <- tol_induced_subtree(ott_ids = ott_id(taxa))

ott_id <- c(735120,
            822554,
            624010,
            192676,
            758338,
            798206,
            121350,
            5615589,
            489952,
            34149,
            5258348,
            228384,
            5234725,
            733690,
            5672942,
            452912,
            707394,
            707397
            )

taxa <- as.data.frame(cbind(litmics, ott_id)) %>%
  mutate(search_string = litmics) %>%
  left_join(taxa) %>%
  mutate(ott_id = paste("ott", ott_id, sep = ""))
```

```{r}

choosetips <- sapply(taxa$ott_id, function(x) grep(paste(x, "$", sep = ""), tree$tip.label))
tipnames <- lapply(choosetips, function(x) tree$tip.label[x])
taxa$tips <- unlist(tipnames)

subtree <- keep.tip(tree, taxa$tips)
```



# Adding info on responders/non-responders

```{r create frame of info for aesthetics}
resp.stat <- c("r", "n", "n", "n", "n", "r", "r", "r", "r", "n", "n", "n", "r", "r", "r", "r", "n", "n")
resp.ref <- c("r", "r", "r", "r", "r", "r", "g", "g", "g", "g", "g", "g", "m", "m", "m", "m", "m", "m")

resp.key <- as.data.frame(cbind(search_string = litmics, resp.stat, resp.ref)) %>%
  mutate(fixed = "hold") 

resp.key <- taxa %>%
  dplyr::select(search_string, tips, unique_name) %>%
  left_join(resp.key) %>%
  mutate(tip.label = tips,
         unique_name = gsub("Ruminiclostridium", "[Clostridium]", unique_name)) %>%
  dplyr::select(tip.label, resp.stat, resp.ref, unique_name)

resp.key$unique_name[15] <- "Klebsiella pneumoniae"
```

```{r create dendrogram}
tree.plot <- ggtree(subtree)  %<+%
  resp.key + 
  geom_tiplab(aes(color = resp.stat, label = unique_name), geom = "text", offset = 0.2) +
  scale_color_manual(breaks = c("n", "r"), values = c("darkred", "black")) +
  geom_tippoint(aes(shape = resp.ref), size = 5) +
  scale_shape_manual(breaks = c("g", "m", "r"), values = c("square", "circle", "triangle")) +
  geom_cladelabel(node = 30, label = "Bacteroidetes \n(Gopalakrishnan)", 
                  geom = "text", color = "darkred", offset = -2.3, offset.text = -2.7, 
                  align = TRUE, vjust = 0) +
  geom_cladelabel(node = 22, label = "Firmicutes \n(Gopalakrishnan)", 
                  geom = "text", color = "black", offset = -4.3, offset.text = -2.6, align = TRUE) +
  xlim(c(0,11.5)) 
  
tree.plot
```

```{r}
getord <- ladderize(subtree, right = FALSE)
is_tip <- getord$edge[,2] <= length(getord$tip.label)
ordered_tips <- getord$edge[is_tip, 2]
order <- subtree$tip.label[ordered_tips]
```

# Accompanying susceptibility heatmap
```{r define data for heatmap}
m <- "m"
n <- "n"
y <- "y"

ceph <- c(n,n,n,n,n,y,y,y,y,y,y,n,n,n,n,n,y,n)
pip <- c(y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,n)
amclac <- c(y,y,y,y,y,y,n,y,y,y,y,y,y,y,y,y,y,y)
clin <- c(y,y,y,y,y,y,n,y,y,y,y,n,n,n,n,n,y,y)
fq <- c(y,y,y,y,y,n,y,y,y,y,y,y,y,y,y,y,y,y)
macr <- c(y,y,y,y,y,y,n,y,y,y,y,n,n,n,n,n,y,y)
metr <- c(y,y,y,y,y,n,y,n,n,n,n,y,y,y,y,y,y,n)
trim <- c(n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,y)
van <- c(n,n,n,n,n,n,y,y,y,y,y,y,y,y,y,y,n,n)
tetr <- c(y,y,y,y,y,y,n,y,y,y,y,y,y,y,y,y,y,y)
line <- c(y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,n)

susc <- as.data.frame(cbind(taxon = rev(order), 
                            Cephalosporins = ceph, 
                            Piperacillin = pip, 
                            Amoxicillin = amclac,  
                            Clindamycin = clin, 
                            Fluoroquinolone = fq, 
                            Macrolide = macr, 
                            Metronidazole = metr, 
                            Sulfamethoxazole = trim, 
                            Vancomycin = van, 
                            Tetracycline = tetr, 
                            Linezolid = line)) %>%
  gather(-taxon, key = "Antibiotic", value = Effective)
```

```{r construct heatmap}
heat <- ggplot(data = susc, aes(fct_relevel(taxon, order), 
                                fct_relevel(Antibiotic, c("Cephalosporins", "Piperacillin", "Amoxicillin",
                                                          antiorder[-1])))) + 
  geom_tile(aes(fill = Effective, color = "black")) +
  scale_fill_manual(breaks = c("yes", "no"), values = c("lightcyan1", "seagreen")) +
  scale_color_manual(breaks = "black", values = "grey85") +
  coord_flip() +
  labs(x = "", y = "") +
  scale_y_discrete(breaks = c("Cephalosporins", "Piperacillin", "Amoxicillin", "Clindamycin", "Vancomycin",
                              "Sulfamethoxazole", "Tetracycline", "Fluoroquinolone", "Macrolide", "Metronidazole",
                              "Linezolid"),
                   labels = c("Cephalosporins", "Piperacillin-Tazobactam", "Amoxicillin-Clavulanate", 
                              "Clindamycin", "Vancomycin", "Sulfamethoxazole-Trimethoprim", "Tetracycline",
                              "Fluoroquinolone", "Macrolide", "Metronidazole", "Linezolid")) +
  theme_bw() +
  theme(axis.text.x = element_text(hjust = 1, angle = 45, size = 10),
        axis.text.y = element_blank(), axis.ticks.y = element_blank(),
        legend.position = "none")

heat
```

# Arrange and save the results

```{r}

test2 <- grid.arrange(
  grobs = list(tree.plot, heat),
   widths = c(2,1.2),
   heights = c(0, 1, .205),
   layout_matrix = rbind(c(NA,2),
                         c(1,2),
                         c(NA,2))
) 


test2

```

# Fisher's exact tests

Counting
```{r}
test <- susc %>%
  mutate(tip.label = ifelse(taxon == "Klebsiella pneumoniae (species in domain Eukaryota)", 
                            "Klebsiella pneumoniae", as.character(taxon))) %>%
  left_join(resp.key)

test2 <- test %>%
  group_by(Antibiotic, Effective, resp.stat) %>%
  tally() %>%
  arrange(Antibiotic, Effective, resp.stat)
```

Ammoxicillin-Clavulanate
```{r}
x <- c(1,0,8,9)
y <- matrix(x, ncol = 2)
fisher.test(y)
```

Cephalosporin
```{r}
x <- c(7,4,2,5)
y <- matrix(x, ncol = 2)
fisher.test(y)
```

Fluoroquinolone
```{r}
x <- c(0,1,9,8)
y <- matrix(x, ncol = 2)
fisher.test(y)
```


Linezolid
```{r}
x <- c(0,1,9,8)
y <- matrix(x, ncol = 2)
fisher.test(y)
```

Macrolide
```{r}
x <- c(4,2,5,7)
y <- matrix(x, ncol = 2)
fisher.test(y)
```

Metronidazole
```{r}
x <- c(1,5,8,4)
y <- matrix(x, ncol = 2)
fisher.test(y)
```

Piperacillin-Tazobactam
```{r}
x <- c(0,1,9,8)
y <- matrix(x, ncol = 2)
fisher.test(y)
```

Sulfamethoxazole-Trimethoprim
```{r}
x <- c(9,8,0,1)
y <- matrix(x, ncol = 2)
fisher.test(y)
```

Tetracycline
```{r}
x <- c(1,0,8,9)
y <- matrix(x, ncol = 2)
fisher.test(y)
```

Vancomycin
```{r}
x <- c(4,4,5,5)
y <- matrix(x, ncol = 2)
fisher.test(y)
```


