---
title: "Code to produce Figure 1: Summary of all medication effects at iostart"
author: "Rebecca Hoyd"
date: "May 10, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(survival)
library(survminer)
library(glue)
library(RColorBrewer)
library(forcats)
library(UpSetR)
```

```{r load data}
db <- readRDS("db.RDS")
```

```{r}
check.window <- function(vect, per){
  wind <- per[1]:per[2]
  wind <- glue_collapse(as.character(wind), sep = ",|,")
  wind <- paste(",", wind, ",", sep = "")
  ifelse(grepl(pattern = wind, x = vect), 1, 0)
}

db <- db %>%
  mutate(abxdays.to.iostart = paste(",", abxdays.to.iostart, ",", sep = ""),
         sterdays.to.start = paste(",", sterdays.to.start, ",", sep = ""),
         abx.28.28 = check.window(abxdays.to.iostart, c(-28,28)),
         steroid.28.28 = check.window(sterdays.to.start, c(-28,28)))
```


```{r define interesting columns}
meds_iostart <- c("h2b_iostart", "nsaid_iostart", "ppi", "statin", "steroid.28.28", "abx.28.28")

allcancers <- unique(db$cancer.name)[1:7]
```

# A) Survival curves of each medication at iostart

```{r create survival plots}
forms <- list()
for(var in meds_iostart){
  forms[[var]] <- as.formula(paste("Surv(days, vitalstatus) ~ ", var, sep = ""))
}

sfits <- surv_fit(formula = forms, data = db)
names(sfits) <- meds_iostart

almeds.plots <- ggsurvplot(sfits, pval = TRUE, conf.int = FALSE, risk.table = TRUE,title = "", legend.title = "", legend.labs = list(c("Not prescribed", "Prescribed")), ylab = "", xlab = "Days", palette = c("slateblue2", "lightsalmon2"), fontsize = 6, font.legend = list(size = 12))
```

```{r save survival plots}
# lapply(meds_iostart, function(x) ggsave(print(almeds.plots[[x]]), filename = paste("../figures/Figure-1/surv-curve_", x, ".png", sep = ""), device = "png"))
```

```{r retain full cohort info for heatmap}
almeds.pval <- lapply(sfits, function (x) surv_pvalue(x)[1,2])
names(almeds.pval) <- names(sfits)
almeds.hr <- lapply(forms, function(x)  coefficients(summary(coxph(formula = x, data = db)))[,2])

almeds.pval <- bind_rows(almeds.pval)
almeds.hr <- bind_rows(almeds.hr)

almeds.dat <- as.data.frame(bind_rows(almeds.pval, almeds.hr))
rownames(almeds.dat) <- c("p.value", "hazrat")

almeds.dat <- almeds.dat %>%
  t() %>%
  as.data.frame() %>%
  rownames_to_column(var = "meds") %>%
  mutate(labcol = ifelse(hazrat < 1, "red", "black"),
         cancer = "All",
         ns = "", 
         labtext = "") %>%
  select(cancer, meds, p.value, hazrat, ns,labtext, labcol)
  
```

# NotDetermined) Upsetr plot

```{r prep for upset}
dat.for.upset <- db %>%
  select(meds_iostart)

colnames(dat.for.upset) <- c("H2B", "NSAIDs", "PPI", "Statins", "Steroids", "Antibiotics")
```

```{r save upset}
# png("../figures/Figure-1/upset_all-meds-confounding.png", units = "in", height = 5, width = 8, res = 600)

upset(dat.for.upset, main.bar.color = "darkred", mainbar.y.label = "Number of Patients", matrix.color = "dark blue", sets.x.label = "")

# dev.off()
```


# Also NotDetermined) Heatmap of values when split by cancer

```{r, message=FALSE, warning=FALSE}
curvesbycancer <- list()
sfits <- list()

pvalbycancer <- list()
pvals <- list()

hrbycanc <- list()
hazrat <- list()

labcol <- list()
labs <- list()

patientsbycanc <- list()
patients <- list()

for(c in allcancers){
  
  tmp <- subset(db, db$cancer.name == c)
  
  for(s in meds_iostart){
    
    n1 <- sum(tmp[[s]], na.rm = TRUE)
    n0 <- tmp[tmp[[s]] == 0,]
    n0 <- length(n0$days)
    patients[[s]] <- paste(n0, n1, sep = ", ")
    
    f <- as.formula(paste("Surv(days, vitalstatus) ~ ", s, sep = ""))
    try ({
      
      sfits[[s]] <- surv_fit(formula = f, data = tmp)
      pvals[[s]] <- surv_pvalue(sfits[[s]])[1,2]
      
      x <- coefficients(summary(coxph(formula = f, data = tmp)))[,2]
      hazrat[[s]] <- ifelse(x > 10, ">10", as.character(round(x, 2)))
      labs[[s]] <- ifelse(x < 1, "red", "black")
      
    })
  }
  
  curvesbycancer[[c]] <- sfits
  pvalbycancer[[c]] <- pvals
  patientsbycanc[[c]] <- patients
  hrbycanc[[c]] <- hazrat
  labcol[[c]] <- labs
  
  sfits <- list()
  pvals <- list()
  patients <- list()
  hazrat <- list()
  labs <- list()
  
}


allcancpvals <- bind_rows(pvalbycancer)
#allcancpvals <- as.data.frame(sapply(allcancpvals, function(x) ifelse(is.na(x), 10, x)))
rownames(allcancpvals) <- names(pvalbycancer)

patientsbycanc <- bind_rows(patientsbycanc)
rownames(patientsbycanc) <- names(pvalbycancer)

labcol <- bind_rows(labcol) 
rownames(labcol) <- names(pvalbycancer)

stickersbycanc <- bind_rows(hrbycanc)
rownames(stickersbycanc) <- names(pvalbycancer)
```

```{r}
pat <- patientsbycanc %>%
  rownames_to_column(var = "cancer") %>%
  gather(key = "meds", value = "ns", -cancer)

labcol <- labcol %>%
  rownames_to_column(var = "cancer") %>%
  gather(key = "meds", value = "labcol", -cancer) %>%
  mutate(labcol = ifelse(is.na(labcol), "black", labcol))

stickersbycanc <- stickersbycanc %>%
  rownames_to_column(var = "cancer") %>%
  gather(key = "meds", value = "hazrat", -cancer) %>%
  full_join(pat) %>%
  mutate(labtext = paste(ns, hazrat, sep = "\n"))

heat.data <- as.data.frame(allcancpvals)  %>%
  rownames_to_column(var = "cancer") %>%
  gather(key = "meds", value = "p.value", -cancer) %>%
  full_join(stickersbycanc) %>%
  full_join(labcol)
```

```{r}
heat.data$hazrat <- as.numeric(heat.data$hazrat)
heat.data <- bind_rows(almeds.dat, heat.data)
```

```{r}
heat.plot <- heat.data %>%
  ggplot(aes(meds, fct_relevel(cancer, "Other", "Bladder Cancer", "Head and Neck Carcinoma", "Melanoma", "Non-Small Cell Lung Cancer", "Renal Cell Carcinoma", "Sarcoma", "All"))) +
  geom_tile(aes(fill = p.value)) +
  labs(x = "", y = "") +
  geom_point(aes(shape = labcol), size = 5) +
  scale_fill_distiller(guide = "legend", breaks = c(0.000000000001, 0.01, 0.02, 0.03, 0.04, 0.05, 0.1, 0.2, 0.5, 1), limits = c(0, 1), values = c(0.000000000001, 0.01, 0.02, 0.03, 0.04, 0.05, 0.1, 0.2, 0.5, 1), type = "div", palette = "RdBu", direction = 1, labels = c("<0.01", "0.01", "0.02","0.03", "0.04","0.05","0.1", "0.2", "0.5", "1")) +
  scale_shape_manual(breaks = c("black", "red"), values = c("-", "+"), labels = c("HR>1", "HR<1"), name = "Direction") +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  scale_x_discrete(breaks = meds_iostart, labels = c("H2B", "NSAIDs", "PPI", "Statins", "Steroids", "Antibiotics")) +
  scale_y_discrete(breaks = c("Other", "Bladder Cancer", "Head and Neck Carcinoma", "Melanoma", "Non-Small Cell Lung Cancer", "Renal Cell Carcinoma", "Sarcoma", "All"), labels = c("Other", "Bladder Cancer", "Head and Neck\nCarcinoma", "Melanoma", "Non-Small Cell\nLung Cancer", "Renal Cell\nCarcinoma", "Sarcoma", "All"))

heat.plot

```

```{r}
# ggsave(plot = heat.plot, filename = "../figures/Figure-1/heatmap_pvalues-by-cancer.png", width = 5, height = 7, device = "png")
```