---
title: "ATB and Steroid contents of other category"
author: "Rebecca Hoyd"
date: "June 19, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(flextable)

```

# Load data
```{r}
db <- readRDS("db.RDS")
othatb <- readRDS("othabx-breakdown.RDS")


```

# Functions 
```{r}
check.window <- function(vect, per){
  wind <- per[1]:per[2]
  wind <- glue_collapse(as.character(wind), sep = ",|,")
  wind <- paste(",", wind, ",", sep = "")
  ifelse(grepl(pattern = wind, x = vect), 1, 0)
}
```

# Other steroid contents
```{r}
statesofinterest <- c("Betamethasone", "Fludrocortisone", "Prednisolone")

edges <- c(-28,28)

for(s in statesofinterest){
  db[[paste(s, ".to.start", sep = "")]] <- paste(",", db[[paste(s, ".to.start", sep = "")]], ",", sep = "") 
  db[[s]] <- check.window(db[[paste(s, ".to.start", sep = "")]], edges)
}

db$Other.Steroid <- ifelse(db$Betamthasone == 1 | db$Fludrocortisone == 1 | db$Prednisolone == 1, 1, 0)
```

```{r}
othster.tab <- db %>%
  filter(Other.Steroid == 1) %>%
  summarise(Betamethasone = sum(Betamethasone),
            Fludrocortisone = sum(Fludrocortisone), 
            Prednisolone = sum(Prednisolone),
            Total = sum(Other.Steroid)) %>%
  t() %>%
  as.data.frame() %>%
  rownames_to_column(var = "Steroid") %>%
  mutate(n = V1) %>%
  select(-V1)

othster.tab %>%
  flextable()
```

```{r}
#write.csv(othster.tab, "../tables/supplemental/other-steroid-quantities.csv")
```

# Antibacterials

```{r}
othatb.tab <- othatb %>%
  group_by(oth.presc.28) %>%
  tally() %>%
  mutate(ATB = oth.presc.28) %>%
  select(ATB, n)
 

othatb.tab %>%
  flextable()
```

```{r}
#write.csv(othatb.tab, "../tables/supplemental/other-atb-quantities.csv")
```