---
title: 'Figure 4: combined model'
author: "Rebecca Hoyd"
date: "July 1, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(survminer)
library(survival)
library(survMisc)
library(ggplot2)
library(dplyr)
library(tidyr)
library(glue)
library(broom)
```


```{r}
db <- readRDS("../data/from_processing/deidentdb_timing.RDS")
```

```{r}
check.window <- function(vect, per){
  wind <- per[1]:per[2]
  wind <- glue_collapse(as.character(wind), sep = ",|,")
  wind <- paste(",", wind, ",", sep = "")
  ifelse(grepl(pattern = wind, x = vect), 1, 0)
}

```

```{r}
to.other <- c("breast cancer", "merkel cell carcinoma", "pancreatic cancer", "Prostate", "small cell lung cancer", "colon cancer", "Hodgkin lymphoma")
db$cancer.name <-  ifelse(db$cancer.name %in% to.other, "Other", db$cancer.name)

capcanc <- as.data.frame(cbind(cancer.name = c("Other", "bladder cancer", "head and neck carcinoma", "melanoma", "non-small cell lung cancer", "renal cell carcinoma", "Sarcoma"), cap.cancer.name = c("Other", "Bladder Cancer", "Head and Neck Carcinoma", "Melanoma", "Non-Small Cell Lung Cancer", "Renal Cell Carcinoma", "Sarcoma")))

db <- db %>%
  left_join(capcanc) %>%
  mutate(cancer.name = cap.cancer.name)

db <- db %>%
  mutate(abxdays.to.iostart = paste(",", abxdays.to.iostart, ",", sep = ""),
         sterdays.to.start = paste(",", sterdays.to.start, ",", sep = ""),
         abx.28.28 = check.window(abxdays.to.iostart, c(-28,28)),
         steroid.28.28 = check.window(sterdays.to.start, c(-28,28)))
```


#Combined model split by cancer
```{r}
db <- db %>%
  filter(staging != 5) %>%
  mutate(ATB = abx.28.28,
         CS = steroid.28.28,
         ECOG = ecog,
         BMI = bmi.calc,
         Sex = sex,
         Age = age) %>%
  drop_na(days, vitalstatus)

allcancers <- unique(db$cancer.name)[1:7]
```

```{r}
res.by.canc <- list()
for(c in allcancers){
  
  tmp <- db %>%
    filter(cancer.name == c)
  n.atb <- sum(tmp$ATB)
  n.cs <- sum(tmp$CS)
  n.all <- length(tmp$cancer.name)
  
  res.by.canc[[c]] <- coxph(Surv(days, vitalstatus) ~ ATB + CS + ECOG + BMI + Sex + Age, data = tmp) %>%
    tidy() %>%
    filter(term == "ATB"|term == "CS") %>%
    mutate(Ref = NA, `Cancer Type` = c, `Drug Type` = term, Timing = "+/- 28", `Sig PFS` = NA, `Sig OS` = ifelse(p.value < .05, "Yes", "No"), `N drug Users` = c(n.atb, n.cs), `N total` = n.all, `PFS HR` = NA, `OS HR` = exp(estimate), `Uni vs Multi Variate` = "Multi", Covariates = ifelse(term == "ATB", "CS, ECOG, BMI, Sex, Age", "ATB, ECOG, BMI, Sex, Age")) %>%
    select(Ref, `Cancer Type`, `Drug Type`, Timing, `Sig PFS`, `Sig OS`, `N drug Users`, `N total`, `PFS HR`, `OS HR`, `Uni vs Multi Variate`, `Covariates`)

}

res.by.canc <- bind_rows(res.by.canc)
```

```{r}
#write.csv(res.by.canc, "../tables/Table_2/Table_2-our-results.csv", row.names = FALSE)
```