---
output:
  html_document: default
  pdf_document: default
  word_document: default
title: Concomitant medications affect overall survival in cancer patients undergoing immunotherapy
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(tableone)
library(forcats)
library(glue)
```

```{r data}

db <- readRDS("db.RDS")

db <-
  db %>%
  drop_na(vitalstatus, days)
```

```{r}
check.window <- function(vect, per){
  wind <- per[1]:per[2]
  wind <- glue_collapse(as.character(wind), sep = ",|,")
  wind <- paste(",", wind, ",", sep = "")
  ifelse(grepl(pattern = wind, x = vect), 1, 0)
}

db <- db %>%
  mutate(abxdays.to.iostart = paste(",", abxdays.to.iostart, ",", sep = ""),
         sterdays.to.start = paste(",", sterdays.to.start, ",", sep = ""),
         abx.28.28 = check.window(abxdays.to.iostart, c(-28,28)),
         steroid.28.28 = check.window(sterdays.to.start, c(-28,28)))
```


```{r prepare dataset}
ionames <- as.data.frame(cbind(immunotherapy = c(1,2,3,4,5,6,7,8,9,10), Immunotherapy = c("Nivolumab", "Pembrolizumab", "Atezolizumab", "Ipilimumab", "Nivolumab + Ipilimumab", "Durvalumab + Tremelimumab", "Tremelimumab", "Nivolumab + Chemotherapy", "Durvalumab", "Other"))) %>%
  mutate(immunotherapy = as.numeric(as.character(immunotherapy)))


coxdf <- 
  db %>%
  select(vitalstatus, age, bmi.calc, ecog,
         sex, cancer.name, statin, ppi, nsaid_iostart, h2b_iostart, immunotherapy, other_io, staging, abx.28.28,
         steroid.28.28, comorb.score) %>%
  left_join(ionames) %>%
  mutate(ECOG = ecog,
         Staging  = ifelse(staging == 5, "Unknown", staging),
         BMI = bmi.calc,
         Age = age,
         Cancer = cancer.name, 
         Sex = sex,
         `ATB within 28 days of ICI` = abx.28.28,
         `CS within 28 days of ICI` = steroid.28.28, 
         `Charleson Comorbidity Score` = ifelse(comorb.score == 0, "0", 
                                                ifelse(comorb.score < 3, "1-2", ">=3")))

coxdf$Immunotherapy <- fct_relevel(coxdf$Immunotherapy, "Atezolizumab", "Durvalumab", "Durvalumab + Tremelimumab", "Ipilimumab", "Nivolumab", "Nivolumab + Ipilimumab", "Nivolumab + Chemotherapy", "Pembrolizumab", "Tremelimumab", "Other")

coxdf$Cancer <- fct_relevel(coxdf$Cancer, "Bladder Cancer", "Head and Neck Carcinoma", "Melanoma", "Non-Small Cell Lung Cancer", "Renal Cell Carcinoma", "Sarcoma", "Other")
```

```{r table 1}
listVars <- c("BMI", "Age", "Sex", "ECOG","Cancer", "Staging", "Charleson Comorbidity Score", "Immunotherapy", "ATB within 28 days of ICI", "CS within 28 days of ICI")
catVars <- c("Sex", "Cancer", "Immunotherapy", "ECOG", "Staging", "ATB within 28 days of ICI", "CS within 28 days of ICI", "Charleson Comorbidity Score")
table1 <- CreateTableOne(vars = listVars,
                         data = coxdf,
                         factorVars = catVars)
table1
```



