---
output:
  html_document: default
  pdf_document: default
  word_document: default
title: Table 1. Cohort characteristics
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(tableone)
library(forcats)
library(glue)
```

```{r data}

db <- readRDS("db.RDS")

db <-
  db %>%
  drop_na(vitalstatus, days)
```

```{r}
check.window <- function(vect, per){
  wind <- per[1]:per[2]
  wind <- glue_collapse(as.character(wind), sep = ",|,")
  wind <- paste(",", wind, ",", sep = "")
  ifelse(grepl(pattern = wind, x = vect), 1, 0)
}

db <- db %>%
  mutate(abxdays.to.iostart = paste(",", abxdays.to.iostart, ",", sep = ""),
         sterdays.to.start = paste(",", sterdays.to.start, ",", sep = ""),
         abx.28.28 = check.window(abxdays.to.iostart, c(-28,28)),
         steroid.28.28 = check.window(sterdays.to.start, c(-28,28)))
```


```{r prepare dataset}
# Create key for naming immunotherapy codes
ionames <- data.frame(immunotherapy = c(1,2,3,4,5,6,7,8,9,10), 
                      Immunotherapy = c("Nivolumab", "Pembrolizumab", 
                                        "Atezolizumab", "Ipilimumab", 
                                        "Nivolumab + Ipilimumab", 
                                        "Durvalumab + Tremelimumab", 
                                        "Tremelimumab", "Nivolumab + Chemotherapy",
                                        "Durvalumab", "Other"),
                      stringsAsFactors = FALSE)

# Select and adjust dataframe for Table 1
coxdf <- 
  db %>%
  select(vitalstatus, age, bmi.calc, ecog, sex, cancer.name, statin, ppi, 
         nsaid_iostart, h2b_iostart, immunotherapy, other_io, staging, abx.28.28,
         steroid.28.28) %>%
  left_join(ionames) %>%
  mutate(ECOG = ecog,
         Staging  = ifelse(staging == 5, "Unknown", staging),
         BMI = bmi.calc,
         Age = age,
         Cancer = cancer.name, 
         Sex = sex,
         `ATB within 28 days of ICI` = abx.28.28,
         `CS within 28 days of ICI` = steroid.28.28,
          Immunotherapy = ifelse(Immunotherapy == "Nivolumab + Chemotherapy",
                                "Other", Immunotherapy),
         Immunotherapy = as.factor(Immunotherapy),
         Immunotherapy = fct_relevel(Immunotherapy, "Atezolizumab", "Durvalumab",
                                     "Durvalumab + Tremelimumab", "Ipilimumab", 
                                     "Nivolumab", "Nivolumab + Ipilimumab", 
                                     "Pembrolizumab", "Tremelimumab", "Other"),
         Cancer = fct_relevel(Cancer, "Bladder Cancer", "Head and Neck Carcinoma",
                              "Melanoma", "Non-Small Cell Lung Cancer", 
                              "Renal Cell Carcinoma", "Sarcoma", "Other")
  )
```

# Creating table 1

```{r table 1}
listVars <- c("BMI", "Age", "Sex", "ECOG", "Cancer", "Staging", "Immunotherapy",
              "ATB within 28 days of ICI", "CS within 28 days of ICI")
catVars <- c("Sex", "Cancer", "Immunotherapy", "ECOG", "Staging", 
             "ATB within 28 days of ICI", "CS within 28 days of ICI")
table1 <- CreateTableOne(vars = listVars,
                         data = coxdf,
                         factorVars = catVars)
table1
```


# Supplemental tables

## Stratifications by medications

### ATB

```{r}
listVars <- c("BMI", "Age", "Sex", "ECOG",  "Cancer", "Staging", "Immunotherapy",
              "ATB within 28 days of ICI", "CS within 28 days of ICI")
catVars <- c("Sex", "Cancer", "Immunotherapy", "ECOG", "Staging", 
             "ATB within 28 days of ICI", "CS within 28 days of ICI")
table.S1 <- CreateTableOne(vars = listVars,
                           strata = "ATB within 28 days of ICI",
                           data = coxdf,
                           factorVars = catVars,
                           argsNonNormal = listVars,
                           argsNormal = list(NULL)
)

table.S1
```

### CS

```{r}
listVars <- c("BMI", "Age", "Sex", "ECOG", "CCI", "Cancer", "Staging", 
              "Immunotherapy", "ATB within 28 days of ICI", 
              "CS within 28 days of ICI")
catVars <- c("Sex", "Cancer", "Immunotherapy", "ECOG", "Staging",
             "ATB within 28 days of ICI", "CS within 28 days of ICI")
table.S2 <- CreateTableOne(vars = listVars,
                           data = coxdf,
                           factorVars = catVars,
                           strata = "CS within 28 days of ICI",
                           argsNonNormal = listVars,
                           argsNormal = list(NULL)
)

table.S2
```



